### ISSUE TITLE
I encountered an issue while configuring the environment

### ISSUE THREAD

**Issue by mrmusad** [Cassie-Lim/saycan#1]
![image](https://github.com/Cassie-Lim/saycan/assets/148746846/25307f4c-cfaa-4b48-bf55-3b2391dd706e)
and i'm unable to find jaxlib==0.4.9+cuda11. cudnn86 in the jaxlib version library
![image](https://github.com/Cassie-Lim/saycan/assets/148746846/57b6c4e0-2f31-4609-9b1e-840f1d592daa)

**Comment by Cassie-Lim** [comment]
Hi, the path to the cuda wheels changed (see: https://github.com/google/jax?tab=readme-ov-file#instructions).
You can find jaxlib==0.4.9+cuda11 in this link: https://[storage.googleapis.com/jax-releases/jax_cuda_releases.html](https://storage.googleapis.com/jax-releases/jax_cuda_releases.html)
<img width="498" alt="image" src="https://github.com/Cassie-Lim/saycan/assets/98252468/f00983fb-665c-41fb-8d9e-01b236456489">
